# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: avondale <avondale@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/04/20 15:14:34 by athawebo          #+#    #+#              #
#    Updated: 2023/05/14 22:48:52 by avondale         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


# Static Libaray name.
NAME		= libft.a

# Header file include dirrectory.
HEAD		= .

# Source dirrectory.
DIRSRC		= ../
CC				= gcc
# CC				= cc

CFLAGS			= -Wall -Wextra -Werror

# ${CC} ../libft.a ft_printf.c && ./a.out
# ${CC} ../libft.a vaArgs.c && ./a.out
# all
test:
# ${CC} ${CFLAGS} ../libftprintf.a ft_printf.c && ./a.out
	${CC} ${CFLAGS} ../libft.a ft_printf.c && ./a.out
# ${CC} ${CFLAGS} ../libft.a chat_2.c && ./a.out
# ${CC} ${CFLAGS} ../libft.a ff.c && ./a.out
# ${CC} ${CFLAGS} ../libft.a ft_pf_chat.c && ./a.out
